### ISSUE TITLE
Email notifications - shop orders

### ISSUE THREAD

**Issue by chayneal** [camerongreen/alq#27]
Is it easy to set up email notifications for shop orders? (We only seem to be getting Paypal payment email which doesn't have full info - eg. t-shirt size).
Not worth spending much time on if this is difficult though, seeming full order details are available through 'Shop / Orders' when logging in to Drupal system.

**Comment by camerongreen** [comment]
OK, so it "seems" set up to do this by default.  Is it doing it at all for anyone (I note some people send payment and move on, whereas others click on "complete" at the end on the alq site)?  Can you check if these are caught in spam or anything?

**Comment by chayneal** [comment]
We get the new member emails. And the Paypal emails for donations or shop
purchases, which include the basic order details, but doesn't include the
full order details such as t-shirt size.
I check the spam etc pretty regularly -- nothing in there.



*Chay Neal*
Email: chayneal@gmail.com
Mobile: 0413 513 650
Facebook <https://www.facebook.com/chayneal> | Twitter
<https://twitter.com/chayneal>
*Animal Liberation Queensland* <http://www.animalliberationqld.org.au/>

**Comment by camerongreen** [comment]
I've added some replacement patterns, let me know how it goes, will close till I hear more :)

**Comment by chayneal** [comment]
Great, will let you know!

Thanks


*Chay Neal*
Email: chayneal@gmail.com
Mobile: 0413 513 650
Facebook <https://www.facebook.com/chayneal> | Twitter
<https://twitter.com/chayneal>
*Animal Liberation Queensland* <http://www.animalliberationqld.org.au/>
