### ISSUE TITLE
Shop/catalogue improvements

### ISSUE THREAD

**Issue by chayneal** [camerongreen/alq#28]
- Bigger preview images for the actual products - eg. http://www.animalliberationqld.org.au/catalog/14
- Images are also a bit blury in the product page, but I'm guessing this is just how the plugin works so probably not worth fixing if its not an easy fix - eg. http://www.animalliberationqld.org.au/content/unisex-t-shirt-vegan-health-environment-animals

**Comment by camerongreen** [comment]
I've made the preview images 50% bigger.  Will work on the blurriness of the images next, it might come down to uploading a separate image, would that be more hassle than it is worth?

**Comment by chayneal** [comment]
Thanks - looks good!

Just on the blurriness... see how if you click the thumbnail it comes up
properly without any blur? But in the thumbnail it is like it isn't resized
properly perhaps?

Not a big deal if too hard to fix anyway. The thumbnails are big enough to
easily see what the shirt looks like and if people want to see a higher
quality image all they need to do is click.




*Chay Neal*
Email: chayneal@gmail.com
Mobile: 0413 513 650
Facebook <https://www.facebook.com/chayneal> | Twitter
<https://twitter.com/chayneal>
*Animal Liberation Queensland* <http://www.animalliberationqld.org.au/>

**Comment by camerongreen** [comment]
Had some time, finally fixed this :)
