### ISSUE TITLE
Membership form to follow monthly donations

### ISSUE THREAD

**Issue by chayneal** [camerongreen/alq#30]
Is it possible to have a copy of the membership form come up after somebody signs up for monthly donations.

As a variant to this, anyone who makes a one-off donation of more than $50, should be offered complimentary 1 year's membership. 

We would want to capture their payment first, as it currently does, but as part of the Thank you page, we could ask for further details for membership...

**Comment by uqcgreen** [comment]
Yes, don't think they would be too hard.

First we'd need to make new forms for both of them, this is done like most content via "create -> webform".  So I imagine we would copy the existing membership sign up form and just remove the payment bit?  That sound like a plan, or would you want different forms in anyway.

Then I think you can say where to redirect to after a payment pretty easily via paypal https://www.paypal.com/au/cgi-bin/webscr?cmd=p/mer/express_return_summary-outside

Which we would make the new webform.  Now matching up the payments and the new member would be an issue, as paypal and the alq site are totally separate, but maybe we worry about that if it becomes a problem.

**Comment by camerongreen** [comment]
OK so I'm thinking a unified membership/donation form that is dynamic.

I tried to find an example but can't really, closest is something like this:

https://donations.hollows.org.au/bespoke/hollows?nonce=20066&return=https%3A//www.hollows.org.au/donate/receipt&v=459ae8e20f2d568abb83008e1a3447cc

We'd have to do the design, but the basic idea is you would click donate and go through to the main page.  It would have a short intro, then have a form which would have some things you click at the top, maybe "membership", "donation", "bequest", anything else you want.

Anyway I'll do a demo and send.

**Comment by chayneal** [comment]
Awesome, sounds good :)


*Chay Neal*
Email: chayneal@gmail.com
Mobile: 0413 513 650
Facebook <https://www.facebook.com/chayneal> | Twitter
<https://twitter.com/chayneal>
*Animal Liberation Queensland* <http://www.animalliberationqld.org.au/>

**Comment by camerongreen** [comment]
Hi Chay,

You'll need to be logged in to see this (not published).

http://alq.org.au/donate-new

It doesn't submit anywhere at the moment, so safe to play around with.

Regards,

Cameron

**Comment by camerongreen** [comment]
Other thoughts:
Should we offer a "no newsletter" option
If someone chooses a family membership, do we need the names of individuals in the household for membership cards etc?
What if someone is already a member, should we extend their membership, what happens with the newsletter etc?

**Comment by chayneal** [comment]
Hey Cameron

Sorry for delay - was in Sydney last week for work and now catching up
again!

Form looks great. Keen to get it up and running as soon as we can.

That's a good question regarding whether someone is already a member. Not
too concerned either way whether we treat as a renewal/extension but we can
probably sort that out ourselves... (although I guess some people may ask
or want to know before they sign up).

Regarding the memebership form -- I reckon just a couple of minor changes:
- address should be mandatory (maybe address line 1, suburb, and postcode)
- rename Town to 'Town/Suburb'
- occupation
(technically in our [very outdated] constitution, we are supposed to record
members name, address and occupation - although I'd be happy to leave
occupation as optional on the form... ).
- maybe a check box to say if they are interested in volunteer
opportunities - eg. "[ ] I am interested in finding out more about
volunteering"
- newsletter option - I'd maybe just reword 'Print by post' in case that
doesn't make sense - perhaps 'Printed newsletter in the post'

I assume if there's minor tweaks needed, ie. adding or removing a field, we
can do those as needed rather than spending too long to make sure everyone
in the office and committee is completely happy before we make it live.

I'm keen to get it up and running as soon as we can. :)




*Chay Neal*
Email: chayneal@gmail.com
Mobile: 0413 513 650
Facebook <https://www.facebook.com/chayneal> | Twitter
<https://twitter.com/chayneal>
*Animal Liberation Queensland* <http://www.animalliberationqld.org.au/>

**Comment by chayneal** [comment]
One other thing - I reckon if they're taking the membership option, then
email opt-in should be ticked by default.


*Chay Neal*
Email: chayneal@gmail.com
Mobile: 0413 513 650
Facebook <https://www.facebook.com/chayneal> | Twitter
<https://twitter.com/chayneal>
*Animal Liberation Queensland* <http://www.animalliberationqld.org.au/>

**Comment by camerongreen** [comment]
Hi Chay,

Cool, hope you had fun in Sydney.

Great that you are happy with the form.  Just so you can know my thinking, the address was mandatory if you selected "by post".  I was just trying to minimise the amount of info someone could put in before changing their mind.  With the volunteering etc, I was thinking stuff like that should go in a follow up survey.  My thinking was if they can't answer a follow up survey, they probably weren't going to be great volunteers anyway :)  Anyway I've made the changes you've asked for but can reinstate.

Now getting it live...see what I did was ignore Paypal's forms, just made a form I liked.  Now getting it to work with their weird ecosystem is another matter.  Should be able to do it by hook or by crook, but will update you.

Regards,

Cameron

**Comment by camerongreen** [comment]
Oh, minimum donation or monthly donation, I put it at $5.

**Comment by camerongreen** [comment]
Hi Chay, I've updated the form if you want a last look before I try to make it work with paypal, otherwise I'll just keep working on it http://alq.org.au/donate-new

**Comment by chayneal** [comment]
Looks good!

For the bequest tab, maybe just tell people to contact the office for
further information for now, and we can update that further later?

I had another thought -- probably best to leave as is for now - but I'm not
actually sure why we have been asking for gender.
Title would probably be more relevant and is probably what's more commonly
used by other orgs.
But changing that would also mean changing fields in the database, so I
think best we leave that for a later change if that's easy enough to change
later?

Thanks Cameron


*Chay Neal*
Email: chayneal@gmail.com
Mobile: 0413 513 650
Facebook <https://www.facebook.com/chayneal> | Twitter
<https://twitter.com/chayneal>
*Animal Liberation Queensland* <http://www.animalliberationqld.org.au/>

**Comment by camerongreen** [comment]
What about this page https://www.givenow.com.au/animalsqld/bequest that was linked from the old site

**Comment by chayneal** [comment]
Hi Cameron

It's probably something we should run past a solicitor at some stage, but I
think the wording attached is the current preferred wording we recommend
(of course, important to remind people to go with the advice of their
solicitor when preparing their Will). Unfortunately I don't have a text so
we'd need to type it up if we want to include it on the web site.

Cheers,
Chay



*Chay Neal*
Email: chayneal@gmail.com
Mobile: 0413 513 650
Facebook <https://www.facebook.com/chayneal> | Twitter
<https://twitter.com/chayneal>
*Animal Liberation Queensland* <http://www.animalliberationqld.org.au/>

**Comment by camerongreen** [comment]
Hi Chay,

When I got deeper into the paypal stuff, I found out I can only pass 255 characters through the form.  This means not much more than name, email etc.  So to get around this, I am passing on what little information I can in the email which will come from paypal.

The full information will be stored in the website, the admin email will link to it.

Do you want to test it out, let me know of any problems and changes.  I will try to test a bit more as well, and once we've ironed out any bugs we can make it live.

Cameron

**Comment by chayneal** [comment]
Thanks Cameron. Sounds good to me.

So you mean we'll just get two emails for donations just like we do for
membership and sales - one from Paypal regarding the payment - and one with
full details from the web form?


*Chay Neal*
Email: chayneal@gmail.com
Mobile: 0413 513 650
Facebook <https://www.facebook.com/chayneal> | Twitter
<https://twitter.com/chayneal>
*Animal Liberation Queensland* <http://www.animalliberationqld.org.au/>

**Comment by camerongreen** [comment]
Yep that's the plan, I was trying to avoid having two.  I'll do some more tests on the code side, but it will be up to you to say when you think it's ok to go live.
